language: node_js
sudo: false
cache: yarn
node_js:
- '10.5'
git:
  depth: 2
jobs:
  include:
  - script: yarn test && yarn build:dev
  - stage: npm
    script: yarn build
    deploy:
      provider: npm
      skip_cleanup: true
      email: hex22a@gmail.com
      api_key:
        secure: dYlG9IkiQzns1iGI/fHt9AW1fFCn//OxsNiVY06TpZcvWXKbAHLQEtjogkqYPP/Jc+rOLQMlfAGync8FLjvTYdV4FJxKW5Vxts561odPrWTjl+utS5e+Csg0n/vX52YDGHGtH+8pxKp5QzBAAA3UdliHyMCRCvuPHRdk0nXleAepX1t0fyuuQJkIcogow766EuxBTtCv7qYJz/Y8WJ9p+CrJpCmtCkqoszYCUdXdSyUCDF5bIPtx6r0CFTKoUtkm1PEVlp8l/hUJm0r5PzjnVb1BMPti3uLGm2t07Mf37Bo8VEzHgsqoHfSuHP2fJewfRdOK0wJ2mz9wQEQvn4IfbheOQK45jCLP97o3ch8p5a4wRhs0hhqbg16mZ+14uqNY0iNox0Ykbm5iBbbUDfjuGDcWfeuAbWNk8F9tJAomE0IqnE/pAQsFpPKhDbUzqOZGsyLEh+EaKGNMlPGiPzl+JImlXVRlCgleuJ94ZUIqsEBJBrbGIVsAlLJwlaPJTXOtAFIoSAXnqqa3aAhgrQvncr6RrsPDztId+8KTO48nH7WAx/3bnvz0NULvRobpcIGnhCuaNaDaouPj2d9CzTiQyfVF9SH0CobqvdBH5wMRkIjj9n+tNRJ95eSvoAFpXdzlbn7+5b8CtbpxN8y/hhkpPRGcgiwzViZeFK3SS3e8ycM=
      on:
        tags: true
        repo: crftd/postcss-glitch
  - stage: github
    install:
      - cd ./demo
      - yarn install
    script:
      - yarn build
    deploy:
      provider: pages
      local_dir: ./demo/dist
      skip_cleanup: true
      github_token:
        secure: WZlUfqicRFjoba0YfajVyp2/vWn7ugiDy+MzvY1PWHe24qN+EbhYUnXTA4RSk+e1mdtdbNzE/MRDHbqI50CUmoyWOHcaFRzZbTRjkRByXXx9cWXW/hjt/dhB7n08nJ9ZyGcLXZTAWHbvbhSfBumCMWQU+dOlEFGUpksZAakN1xpo0o5jiJcZkmo5On1AozkfPecy1RsoWX6pxuAxFaws4hAS2CBAFeq5Gha+0vATYkIPor/XVFLqOlUWFDklKVPXN9VAN1SOpq7DO5iaJ+p9bwdOPANLYZV8zbX2wUmpHFpwH8NuWPGk4LpnGtJyuIMOds3ViSHDbodKttRpYBXqkyvEEtvfsw63iGzZ+CQ4lxHNKhFu4j9fkzZisUkYroNYHG5WFAV/aIQG+aJXCZW2iq58y4M5vB7ifVudeKFJnRVmid4N3GLVMe3XDNCVN1RzugY7caeoqBXM2DHuQXxKPu2yXz2mKLP7++/vCd/t/fOe60MM6ytQwAl5GL5EuiHMG/di8RMMqYPnYSY29bWEwHWgahBiTbGM9zHI+uXH9C+GBvZqJTsfYrr1nv4pFu8MY5iPfh1mGtdE+f60wCm+y/CpPFcSHanIfsmd2nnHPxYqSnrBHC/XVjDdsJ4CGiOdN+6gedcCIRDSW97+VUee2eZBCBCUqH/eFjCCKVKczuA=
      on:
        tags: true
        branch: master
