language: node_js
sudo: false
cache: yarn
node_js:
- '10.5'
git:
  depth: 2
jobs:
  include:
  - script: yarn test && yarn build:dev
  - stage: npm
    script: yarn build
    deploy:
      provider: npm
      skip_cleanup: true
      email: hex22a@gmail.com
      api_key:
        secure: dYlG9IkiQzns1iGI/fHt9AW1fFCn//OxsNiVY06TpZcvWXKbAHLQEtjogkqYPP/Jc+rOLQMlfAGync8FLjvTYdV4FJxKW5Vxts561odPrWTjl+utS5e+Csg0n/vX52YDGHGtH+8pxKp5QzBAAA3UdliHyMCRCvuPHRdk0nXleAepX1t0fyuuQJkIcogow766EuxBTtCv7qYJz/Y8WJ9p+CrJpCmtCkqoszYCUdXdSyUCDF5bIPtx6r0CFTKoUtkm1PEVlp8l/hUJm0r5PzjnVb1BMPti3uLGm2t07Mf37Bo8VEzHgsqoHfSuHP2fJewfRdOK0wJ2mz9wQEQvn4IfbheOQK45jCLP97o3ch8p5a4wRhs0hhqbg16mZ+14uqNY0iNox0Ykbm5iBbbUDfjuGDcWfeuAbWNk8F9tJAomE0IqnE/pAQsFpPKhDbUzqOZGsyLEh+EaKGNMlPGiPzl+JImlXVRlCgleuJ94ZUIqsEBJBrbGIVsAlLJwlaPJTXOtAFIoSAXnqqa3aAhgrQvncr6RrsPDztId+8KTO48nH7WAx/3bnvz0NULvRobpcIGnhCuaNaDaouPj2d9CzTiQyfVF9SH0CobqvdBH5wMRkIjj9n+tNRJ95eSvoAFpXdzlbn7+5b8CtbpxN8y/hhkpPRGcgiwzViZeFK3SS3e8ycM=
      on:
        tags: true
        repo: crftd/postcss-glitch
  - stage: github
    install:
      - cd ./demo
      - yarn install
    script:
      - yarn build
    deploy:
      provider: pages
      local_dir: ./demo/dist
      skip_cleanup: true
      github_token:
        secure: HjwA0EbnSIy4cPwrvyJ3rQAR7+FZ6bAIpRqxhTRU9S3x5ZBB/9nGpa9nS38weUl/a8U23B+63tx7ZnuR0r+CG6ag4/Xq8gzeVeL2JDUU0B6a1tZkbP/A5CfpH19QzbL9tiuj6H9lUy2n5tLJlcd1vYlMjezDu0ZIR/EfIIaII0L/yXMPgVfhF+NzvxxIcbT5Ggi2v3VO5BgNwms4JJYQ1D3MKBw6WDWmerQXXWwM6o/dFHeW6VGYSFuXIpxBhRHaW3GrIoT8FQ4mSX40PhsCvUWh9MRy3AlJqgZEtaFdEFwclDZ0WcbtPI2pT3WRQEIGQqG9FEL1H+QzJ4CNyy0o6l5Gn0FkwXJ9f9/nTx+zS9XeixoHflyFpx23Wyy+NpDyRYCTa7Z9DCIpJTFyDJVVDRchvdt8/sG9E7AwbWPkPdyaXCik9HWHtj+kWtjAFoiEiw5wk94ld27iZ6So4u4x4C2EmhNMdd41+kHa70j/dbzEZgqdznijXg1VwV+7+cVMJT6BwhM863N48lNm/ayl9teLa8kkSCva0UJeXl3ciemM/MFeKKLKQSuSLdM4NAUyXu01rIKTcr5oMEGPwNqK9YRN68fuKvQupOtR5yttg/M45OB8Ty3tnCqGm3IOvrazlAq8QOn92nru0RfFVp5p+LHevJMZiarfl0VsWQkoXEQ=
      on:
        tags: true
        branch: master
