language: node_js
sudo: false
cache: yarn
node_js:
- '10.5'
git:
  depth: 2
jobs:
  include:
  - script: yarn test && yarn build:dev
  - stage: npm
    script: yarn build
    deploy:
      provider: npm
      skip_cleanup: true
      email: hex22a@gmail.com
      api_key:
        secure: dYlG9IkiQzns1iGI/fHt9AW1fFCn//OxsNiVY06TpZcvWXKbAHLQEtjogkqYPP/Jc+rOLQMlfAGync8FLjvTYdV4FJxKW5Vxts561odPrWTjl+utS5e+Csg0n/vX52YDGHGtH+8pxKp5QzBAAA3UdliHyMCRCvuPHRdk0nXleAepX1t0fyuuQJkIcogow766EuxBTtCv7qYJz/Y8WJ9p+CrJpCmtCkqoszYCUdXdSyUCDF5bIPtx6r0CFTKoUtkm1PEVlp8l/hUJm0r5PzjnVb1BMPti3uLGm2t07Mf37Bo8VEzHgsqoHfSuHP2fJewfRdOK0wJ2mz9wQEQvn4IfbheOQK45jCLP97o3ch8p5a4wRhs0hhqbg16mZ+14uqNY0iNox0Ykbm5iBbbUDfjuGDcWfeuAbWNk8F9tJAomE0IqnE/pAQsFpPKhDbUzqOZGsyLEh+EaKGNMlPGiPzl+JImlXVRlCgleuJ94ZUIqsEBJBrbGIVsAlLJwlaPJTXOtAFIoSAXnqqa3aAhgrQvncr6RrsPDztId+8KTO48nH7WAx/3bnvz0NULvRobpcIGnhCuaNaDaouPj2d9CzTiQyfVF9SH0CobqvdBH5wMRkIjj9n+tNRJ95eSvoAFpXdzlbn7+5b8CtbpxN8y/hhkpPRGcgiwzViZeFK3SS3e8ycM=
      on:
        tags: true
        repo: crftd/postcss-glitch
  - stage: github
    install:
      - cd ./demo
      - yarn install
    script:
      - yarn build
    deploy:
      provider: pages
      local_dir: ./demo/dist
      skip_cleanup: true
      github_token:
        secure: lCg1cwGMM1DXiwnQS5+sQplMkFyZgFimOTfuQlAG1y7RPydsvxsJc3wIPX6BEa5SkE+y45I5EqyXE8Z61SvWf7LuzUeTNkW4GLoRiRP+t53cDJcNcyEO9raL27+ftzl2d7tvtXRlil5XSFocqwRJhrcCxM9eczKIwgxW5lwmVYqDxxmvdbD8QBpnd19u6nZeMFk8AozFiJhL4a62Aju7u6bgfhzekiQKP4Gx/zmuZBu88esFoTub668w5Xd1mxNrftSHFzt6Xl8m5X6lINMm52IFu/CWNRhFjEXAE+nuV9jPz0dQLm1gClQYXypfOTpaOFwoNR3MAE+rDwA68RwvbIL7sT8KXHbxsLPtLtQA6atDZ6lkk+qhEyd5+ik5PgFqgsISKoH/dTBy/N7wtkdCc+zVmpULU7ZoklkMgQHMZYodLgSLxqVe8jmrM3P7NvCXmngGKa1Ys/x3NIzTn+7Erja8o2vli7ed3nh5qXp1xiFotsvh/V9Dxchvl44ir1pDEEtSrIoiwBtVkF6Hyd0gXZCjJQI/Ep0z63dckEwFzC6VsF91gOLUGistk36KuBRDo7layOE1yAps7meUFcoWLt4Zu17j6BJAA4pAiM78mdDc5M+viy7Qos6kj3rT/g6TJiUGxJjqZuTCJtj7TnMWcNVbAgSLkx7HfwiGtyGqKgE=
      on:
        tags: true
        branch: master
