language: node_js
sudo: false
cache: yarn
node_js:
- '10.5'
git:
  depth: 2
jobs:
  include:
  - script: yarn test && yarn build:dev
  - stage: npm
    script: yarn build
    deploy:
      provider: npm
      skip_cleanup: true
      email: hex22a@gmail.com
      api_key:
        secure: dYlG9IkiQzns1iGI/fHt9AW1fFCn//OxsNiVY06TpZcvWXKbAHLQEtjogkqYPP/Jc+rOLQMlfAGync8FLjvTYdV4FJxKW5Vxts561odPrWTjl+utS5e+Csg0n/vX52YDGHGtH+8pxKp5QzBAAA3UdliHyMCRCvuPHRdk0nXleAepX1t0fyuuQJkIcogow766EuxBTtCv7qYJz/Y8WJ9p+CrJpCmtCkqoszYCUdXdSyUCDF5bIPtx6r0CFTKoUtkm1PEVlp8l/hUJm0r5PzjnVb1BMPti3uLGm2t07Mf37Bo8VEzHgsqoHfSuHP2fJewfRdOK0wJ2mz9wQEQvn4IfbheOQK45jCLP97o3ch8p5a4wRhs0hhqbg16mZ+14uqNY0iNox0Ykbm5iBbbUDfjuGDcWfeuAbWNk8F9tJAomE0IqnE/pAQsFpPKhDbUzqOZGsyLEh+EaKGNMlPGiPzl+JImlXVRlCgleuJ94ZUIqsEBJBrbGIVsAlLJwlaPJTXOtAFIoSAXnqqa3aAhgrQvncr6RrsPDztId+8KTO48nH7WAx/3bnvz0NULvRobpcIGnhCuaNaDaouPj2d9CzTiQyfVF9SH0CobqvdBH5wMRkIjj9n+tNRJ95eSvoAFpXdzlbn7+5b8CtbpxN8y/hhkpPRGcgiwzViZeFK3SS3e8ycM=
      on:
        tags: true
        repo: crftd/postcss-glitch
  - stage: github
    install:
      - cd ./demo
      - yarn install
    script:
      - yarn build
    deploy:
      provider: pages
      local_dir: ./demo/dist
      skip_cleanup: true
      github_token:
        secure: HxVyG/8s/iL7KuB6CjCbokYz30TyyCRPuny9sw4UvLx4ker/8VoLvZC/E9YorDmTacRtWf4z1+3sqficOmhep4/G4I5fSEpHPdY3dBgEZ1ql4ABdmbuoJRmiEwP98NXjfQZ8qfSCXtsn6FM9PyFty34mo3t7S8qtc26R4/LFsLC/Xo8BcVIMz/+MLEFlCfDGHrN44xyC7jD/zkTUvrPszXLIQABECutT9zFu7kOv+ybyOxUzp9jKF53ciNlbDcXgzx1JHDd8vcYqsE8g+ufDigzV+9BE9JHwxaQfBNAP5hZzydBWJYCw+mC4RGi9OWlAJnIGGaB3io7VLNuHHHPs7K99XB+l2TUUK/hZQGBH84RafJn+gsW3iRMpJ4f2a0V145SAcE4QnDfwbcpeoPcKpxXfEaDRtqaooBIRvWyTxRzIU9fGsoMMGe6VngCgC2TbY3lEteEPrdwgNwpjBFLCheN39tiLCq0R+J8C2M4GqoF3zKfwmTnnTCecFhkagL8VzX9lSVDXg5E1wplLiGKlKTcWf+vzX8KdMnbiEstMbl4OVn2DUG6Ty4CCgj4CzZpRE+9WJoRasd/Iw51TZo+p9E2v8t6v/5qO+UE7m7Ac8u9dKfM/iU9ieKl0HufTmrd3ENpAOM1/m6WxO9h+CEFjH95hY0krxYf0oY6R/+VySJw=
      on:
        tags: true
        branch: master
