version: 2.1
orbs:
  node: circleci/node@3.0.1

defaults: &defaults
  working_directory: ~/repo
  executor:
    name: node/default

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          command: yarn workspace postcss-glitch run test
          name: Run YARN tests
      - persist_to_workspace:
          root: ~/repo
          paths: .
  npm:
    <<: *defaults
    steps:
      - run:
          name: Install yq
          command: |
            wget https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_386
            sudo mv yq_linux_386 /usr/local/bin/yq
            sudo chmod +x /usr/local/bin/yq
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn workspace postcss-glitch build:ci
      - run:
          name: Authenticate with registry
          command: cat root_yarnrc.template.yml | yq w - 'npmRegistries."https://registry.yarnpkg.com".npmAuthToken' $npm_TOKEN > ../.yarnrc.yml
      - run:
          name: Publish package
          command: yarn workspace postcss-glitch npm publish
  gh-pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn workspace simple build
      - run:
          name: Configure GitHub deployer user
          command: |
            git config user.email "hex22a@gmail.com"
            git config user.name "crash-o-matic"
      - add_ssh_keys:
          fingerprints:
            - "c4:94:5d:ec:82:90:0a:b8:bd:4e:2e:fa:03:e7:19:8e"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn workspace simlpe deploy
workflows:
  test-and-deploy:
    jobs:
      - test:
          filters: # required since `npm` has tag filters AND requires `test`
            tags:
              only: /.*/
      - npm:
          filters:
            tags:
              only: /^v?\d+.\d+.\d+$/
            branches:
              ignore: /.*/
          context: publish
          requires:
            - test
      - gh-pages:
          filters:
            tags:
              only: /^(demo-)?v?\d+.\d+.\d+$/
            branches:
              ignore: /.*/
          context: publish
          requires:
            - test
