version: 2.1
orbs:
  node: circleci/node@3.0.1

defaults: &defaults
  working_directory: ~/repo
  executor:
    name: node/default

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          command: yarn workspace postcss-glitch run test
          name: Run YARN tests
      - persist_to_workspace:
          root: ~/repo
          paths: .
  npm:
    <<: *defaults
    steps:
      - run:
          name: Install yq
          command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64 \
            sudo add-apt-repository ppa:rmescandon/yq \
            sudo apt update \
            sudo apt install yq -y
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn workspace postcss-glitch build:ci
      - run:
          name: Authenticate with registry
          command: cat root_yarnrc.template.yml | yq w - 'npmRegistries."https://registry.yarnpkg.com".npmAuthToken' $npm_TOKEN > ../.yarnrc.yml
      - run:
          name: Publish package
          command: yarn workspace postcss-glitch npm publish
  gh-pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn workspace simple build
workflows:
  test-and-deploy:
    jobs:
      - test:
          filters: # required since `npm` has tag filters AND requires `test`
            tags:
              only: /.*/
      - npm:
          filters:
            tags:
              only: /^v?\d+.\d+.\d+/
            branches:
              ignore: /.*/
          context: publish
          requires:
            - test
      - gh-pages:
          filters:
            tags:
              only: /^v?\d+.\d+.\d+/
            branches:
              ignore: /.*/
          context: publish
          requires:
            - test
