version: 2.1
orbs:
  node: circleci/node@3.0.1

defaults: &defaults
  working_directory: ~/repo
  executor:
    name: node/default

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          command: yarn run test
          name: Run YARN tests
      - persist_to_workspace:
          root: ~/repo
          paths: .
  npm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn build:ci
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  test-and-deploy:
    jobs:
      - test:
          filters: # required since `npm` has tag filters AND requires `test`
            tags:
              only: /.*/
      - npm:
          filters:
            tags:
              only: /^v?\d+.\d+.\d+/
            branches:
              ignore: /.*/
          context: publish
          requires:
            - test
